### ISSUE TITLE
The script exit when select 1) 安装

### ISSUE THREAD

**Issue by fyr233** [wangwanjie/ocserv-install#1]
![image](https://github.com/wangwanjie/ocserv-install/assets/36994804/f2a58851-eac6-4c6b-8d90-56e20d532fb3)
Why?
My system: ubuntu 22.04 from AliYun.

**Comment by wangwanjie** [comment]
> ![image](https://github.com/wangwanjie/ocserv-install/assets/36994804/f2a58851-eac6-4c6b-8d90-56e20d532fb3)
> 
> Why?
> 
> My system: ubuntu 22.04 from AliYun.

Sorry, my script has an error on ubuntu. Do you still need this?

**Comment by fyr233** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36994804/310338826-f2a58851-eac6-4c6b-8d90-56e20d532fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTYxNzgsIm5iZiI6MTcxMTY5NTg3OCwicGF0aCI6Ii8zNjk5NDgwNC8zMTAzMzg4MjYtZjJhNTg4NTEtZWFjNi00YzZiLThkOTAtNTZlMjBkNTMyZmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA3MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTgzNDYwNmYyMzhlMDNhZjY5ZWM5Zjc5NzZlN2E0YmNmMDUyOGNkYjczZTMxYzYyMjA3ODA4Yzg1OTYwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gj20YmQDW_CFeEHJL8XAl7tliHqpx_h7lOOXDPfa_xs)
> > Why?
> > My system: ubuntu 22.04 from AliYun.
> 
> Sorry, my script has an error on ubuntu. Do you still need this?

Thanks for reply, I don't need it now. Ocserv seems to be unhappy with ubuntu22. I have changed to ubuntu20.

**Comment by wangwanjie** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/36994804/310338826-f2a58851-eac6-4c6b-8d90-56e20d532fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTYxNzgsIm5iZiI6MTcxMTY5NTg3OCwicGF0aCI6Ii8zNjk5NDgwNC8zMTAzMzg4MjYtZjJhNTg4NTEtZWFjNi00YzZiLThkOTAtNTZlMjBkNTMyZmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA3MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTgzNDYwNmYyMzhlMDNhZjY5ZWM5Zjc5NzZlN2E0YmNmMDUyOGNkYjczZTMxYzYyMjA3ODA4Yzg1OTYwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gj20YmQDW_CFeEHJL8XAl7tliHqpx_h7lOOXDPfa_xs)
> > > Why?
> > > My system: ubuntu 22.04 from AliYun.
> > 
> > 
> > Sorry, my script has an error on ubuntu. Do you still need this?
> 
> Thanks for reply, I don't need it now. Ocserv seems to be unhappy with ubuntu22. I have changed to ubuntu20.

maybe you can have a look at this article
[https://www.linuxbabe.com/ubuntu/openconnect-vpn-server-ocserv-ubuntu-16-04-17-10-lets-encrypt](https://www.linuxbabe.com/ubuntu/openconnect-vpn-server-ocserv-ubuntu-16-04-17-10-lets-encrypt)
